// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using luciadominguez.web.database;

namespace luciadominguez.web.database.Migrations
{
    [DbContext(typeof(SQLiteContext))]
    [Migration("20190415164810_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("luciadominguez.web.domain.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("luciadominguez.web.domain.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AlbumId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Extension");

                    b.Property<string>("FileName");

                    b.Property<int>("Height");

                    b.Property<decimal>("Price");

                    b.Property<string>("Title");

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("luciadominguez.web.domain.PhotoTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("PhotoId");

                    b.Property<Guid?>("TagId");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.HasIndex("TagId");

                    b.ToTable("PhotoTags");
                });

            modelBuilder.Entity("luciadominguez.web.domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("luciadominguez.web.domain.Photo", b =>
                {
                    b.HasOne("luciadominguez.web.domain.Album", "Album")
                        .WithMany("Photos")
                        .HasForeignKey("AlbumId");
                });

            modelBuilder.Entity("luciadominguez.web.domain.PhotoTag", b =>
                {
                    b.HasOne("luciadominguez.web.domain.Photo", "Photo")
                        .WithMany("PhotoTags")
                        .HasForeignKey("PhotoId");

                    b.HasOne("luciadominguez.web.domain.Tag", "Tag")
                        .WithMany("PhotoTags")
                        .HasForeignKey("TagId");
                });
#pragma warning restore 612, 618
        }
    }
}
